version: '3'

services:
  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/code
    ports:
      - "5000:5000"

  postgresql:
      image: postgres
      restart: always
      volumes:
       - ./data/postgresql:/var/lib/postgresql
      environment:
        - POSTGRES_USER=psql_user
        - POSTGRES_PASSWORD=Ab132xw
        - POSTGRES_DB=psql_db
      ports:
        - "5432:5432"

